In [2]:
import numpy as np 

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
a = np.array([1, 2, 3, 4])     
b = np.arange(1, 11)       
c = np.linspace(0, 2, 5)         # 5 numbers between 0 and 1
d = np.random.randint(1, 3, 5) 

print(a)
print(b)
print(c)
print(d)


[1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10]
[0.  0.5 1.  1.5 2. ]
[2 2 1 2 2]


In [18]:
arr = np.arange(12)       # 0 to 11
print(arr)    
print(arr.shape)          # (12,) → 1D
print(arr.ndim)           # 1 dimension
reshaped = arr.reshape(3, 4) # 3x4 matrix
print(reshaped.shape)     # (3,4)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
1
(3, 4)


In [4]:
# From lists
a = np.array([10,20,30])

# Zeros, ones, random
zeros = np.zeros((2,3))
ones = np.ones((3,3))
rand = np.random.rand(2,3)

# Range
arr = np.arange(1,11,2)  # [1,3,5,7,9]
lin = np.linspace(0,1,5) # evenly spaced

print(a)

print(zeros,"\n")

print(ones,"\n")

print(rand,"\n")

print(arr,"\n")

print(lin,"\n")

[10 20 30]
[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0.05144667 0.57650569 0.2778446 ]
 [0.77448706 0.68914266 0.49451007]] 

[1 3 5 7 9] 

[0.   0.25 0.5  0.75 1.  ] 

